<?php
/**
 * TranscoderConfig
 *
 * PHP version 5
 *
 * @category Class
 * @package  WowzaApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Topix\Hackademy\WowzaApi\Model;


/**
 * TranscoderConfig Class Doc Comment
 *
 * @category    Class
 * @package     WowzaApi
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranscoderConfig extends SwaggerModel
 {

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'TranscoderConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'licenses' => 'int',
        'licensed' => 'bool',
        'licensesInUse' => 'int',
        'templates' => TranscoderTemplatesConfig::class,
        'available' => 'bool',
        'serverName' => 'string',
        'saveFieldList' => 'string[]',
        'version' => 'string'
);

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'licenses' => 'licenses',
        'licensed' => 'licensed',
        'licensesInUse' => 'licensesInUse',
        'templates' => 'templates',
        'available' => 'available',
        'serverName' => 'serverName',
        'saveFieldList' => 'saveFieldList',
        'version' => 'version'
);

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'licenses' => 'setLicenses',
        'licensed' => 'setLicensed',
        'licensesInUse' => 'setLicensesInUse',
        'templates' => 'setTemplates',
        'available' => 'setAvailable',
        'serverName' => 'setServerName',
        'saveFieldList' => 'setSaveFieldList',
        'version' => 'setVersion'
);

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'licenses' => 'getLicenses',
        'licensed' => 'getLicensed',
        'licensesInUse' => 'getLicensesInUse',
        'templates' => 'getTemplates',
        'available' => 'getAvailable',
        'serverName' => 'getServerName',
        'saveFieldList' => 'getSaveFieldList',
        'version' => 'getVersion'
);

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['licenses'] = isset($data['licenses']) ? $data['licenses'] : null;
        $this->container['licensed'] = isset($data['licensed']) ? $data['licensed'] : null;
        $this->container['licensesInUse'] = isset($data['licensesInUse']) ? $data['licensesInUse'] : null;
        $this->container['templates'] = isset($data['templates']) ? $data['templates'] : null;
        $this->container['available'] = isset($data['available']) ? $data['available'] : null;
        $this->container['serverName'] = isset($data['serverName']) ? $data['serverName'] : null;
        $this->container['saveFieldList'] = isset($data['saveFieldList']) ? $data['saveFieldList'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['licenses'] === null) {
            $invalid_properties[] = "'licenses' can't be null";
        }
        if ($this->container['licensed'] === null) {
            $invalid_properties[] = "'licensed' can't be null";
        }
        if ($this->container['licensesInUse'] === null) {
            $invalid_properties[] = "'licensesInUse' can't be null";
        }
        if ($this->container['templates'] === null) {
            $invalid_properties[] = "'templates' can't be null";
        }
        if ($this->container['available'] === null) {
            $invalid_properties[] = "'available' can't be null";
        }
        if ($this->container['serverName'] === null) {
            $invalid_properties[] = "'serverName' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalid_properties[] = "'version' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['licenses'] === null) {
            return false;
        }
        if ($this->container['licensed'] === null) {
            return false;
        }
        if ($this->container['licensesInUse'] === null) {
            return false;
        }
        if ($this->container['templates'] === null) {
            return false;
        }
        if ($this->container['available'] === null) {
            return false;
        }
        if ($this->container['serverName'] === null) {
            return false;
        }
        if ($this->container['version'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets licenses
     * @return int
     */
    public function getLicenses()
    {
        return $this->container['licenses'];
    }

    /**
     * Sets licenses
     * @param int $licenses
     * @return $this
     */
    public function setLicenses($licenses)
    {
        $this->container['licenses'] = $licenses;

        return $this;
    }

    /**
     * Gets licensed
     * @return bool
     */
    public function getLicensed()
    {
        return $this->container['licensed'];
    }

    /**
     * Sets licensed
     * @param bool $licensed
     * @return $this
     */
    public function setLicensed($licensed)
    {
        $this->container['licensed'] = $licensed;

        return $this;
    }

    /**
     * Gets licensesInUse
     * @return int
     */
    public function getLicensesInUse()
    {
        return $this->container['licensesInUse'];
    }

    /**
     * Sets licensesInUse
     * @param int $licensesInUse
     * @return $this
     */
    public function setLicensesInUse($licensesInUse)
    {
        $this->container['licensesInUse'] = $licensesInUse;

        return $this;
    }

    /**
     * Gets templates
     * @return  TranscoderTemplatesConfig
     */
    public function getTemplates()
    {
        return $this->container['templates'];
    }

    /**
     * Sets templates
     * @param TranscoderTemplatesConfig $templates
     * @return $this
     */
    public function setTemplates($templates)
    {
        $this->container['templates'] = $templates;

        return $this;
    }

    /**
     * Gets available
     * @return bool
     */
    public function getAvailable()
    {
        return $this->container['available'];
    }

    /**
     * Sets available
     * @param bool $available
     * @return $this
     */
    public function setAvailable($available)
    {
        $this->container['available'] = $available;

        return $this;
    }

    /**
     * Gets serverName
     * @return string
     */
    public function getServerName()
    {
        return $this->container['serverName'];
    }

    /**
     * Sets serverName
     * @param string $serverName
     * @return $this
     */
    public function setServerName($serverName)
    {
        $this->container['serverName'] = $serverName;

        return $this;
    }

    /**
     * Gets saveFieldList
     * @return string[]
     */
    public function getSaveFieldList()
    {
        return $this->container['saveFieldList'];
    }

    /**
     * Sets saveFieldList
     * @param string[] $saveFieldList
     * @return $this
     */
    public function setSaveFieldList($saveFieldList)
    {
        $this->container['saveFieldList'] = $saveFieldList;

        return $this;
    }

    /**
     * Gets version
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     * @param string $version
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
}

}
