<?php
/**
 * VerimatrixStreamMapConfig
 *
 * PHP version 5
 *
 * @category Class
 * @package  WowzaApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Topix\Hackademy\WowzaApi\Model;


/**
 * VerimatrixStreamMapConfig Class Doc Comment
 *
 * @category    Class
 * @package     WowzaApi
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VerimatrixStreamMapConfig extends SwaggerModel
 {

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'VerimatrixStreamMapConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'posCount' => 'int',
        'keyInterval' => 'int',
        'serverName' => 'string',
        'saveFieldList' => 'string[]',
        'version' => 'string',
        'streamName' => 'string',
        'resID' => 'string',
        'order' => 'int'
);

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'posCount' => 'posCount',
        'keyInterval' => 'keyInterval',
        'serverName' => 'serverName',
        'saveFieldList' => 'saveFieldList',
        'version' => 'version',
        'streamName' => 'streamName',
        'resID' => 'resID',
        'order' => 'order'
);

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'posCount' => 'setPosCount',
        'keyInterval' => 'setKeyInterval',
        'serverName' => 'setServerName',
        'saveFieldList' => 'setSaveFieldList',
        'version' => 'setVersion',
        'streamName' => 'setStreamName',
        'resID' => 'setResID',
        'order' => 'setOrder'
);

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'posCount' => 'getPosCount',
        'keyInterval' => 'getKeyInterval',
        'serverName' => 'getServerName',
        'saveFieldList' => 'getSaveFieldList',
        'version' => 'getVersion',
        'streamName' => 'getStreamName',
        'resID' => 'getResID',
        'order' => 'getOrder'
);

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['posCount'] = isset($data['posCount']) ? $data['posCount'] : null;
        $this->container['keyInterval'] = isset($data['keyInterval']) ? $data['keyInterval'] : null;
        $this->container['serverName'] = isset($data['serverName']) ? $data['serverName'] : null;
        $this->container['saveFieldList'] = isset($data['saveFieldList']) ? $data['saveFieldList'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['streamName'] = isset($data['streamName']) ? $data['streamName'] : null;
        $this->container['resID'] = isset($data['resID']) ? $data['resID'] : null;
        $this->container['order'] = isset($data['order']) ? $data['order'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['posCount'] === null) {
            $invalid_properties[] = "'posCount' can't be null";
        }
        if ($this->container['keyInterval'] === null) {
            $invalid_properties[] = "'keyInterval' can't be null";
        }
        if ($this->container['serverName'] === null) {
            $invalid_properties[] = "'serverName' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalid_properties[] = "'version' can't be null";
        }
        if ($this->container['streamName'] === null) {
            $invalid_properties[] = "'streamName' can't be null";
        }
        if ($this->container['resID'] === null) {
            $invalid_properties[] = "'resID' can't be null";
        }
        if ($this->container['order'] === null) {
            $invalid_properties[] = "'order' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['posCount'] === null) {
            return false;
        }
        if ($this->container['keyInterval'] === null) {
            return false;
        }
        if ($this->container['serverName'] === null) {
            return false;
        }
        if ($this->container['version'] === null) {
            return false;
        }
        if ($this->container['streamName'] === null) {
            return false;
        }
        if ($this->container['resID'] === null) {
            return false;
        }
        if ($this->container['order'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets posCount
     * @return int
     */
    public function getPosCount()
    {
        return $this->container['posCount'];
    }

    /**
     * Sets posCount
     * @param int $posCount
     * @return $this
     */
    public function setPosCount($posCount)
    {
        $this->container['posCount'] = $posCount;

        return $this;
    }

    /**
     * Gets keyInterval
     * @return int
     */
    public function getKeyInterval()
    {
        return $this->container['keyInterval'];
    }

    /**
     * Sets keyInterval
     * @param int $keyInterval
     * @return $this
     */
    public function setKeyInterval($keyInterval)
    {
        $this->container['keyInterval'] = $keyInterval;

        return $this;
    }

    /**
     * Gets serverName
     * @return string
     */
    public function getServerName()
    {
        return $this->container['serverName'];
    }

    /**
     * Sets serverName
     * @param string $serverName
     * @return $this
     */
    public function setServerName($serverName)
    {
        $this->container['serverName'] = $serverName;

        return $this;
    }

    /**
     * Gets saveFieldList
     * @return string[]
     */
    public function getSaveFieldList()
    {
        return $this->container['saveFieldList'];
    }

    /**
     * Sets saveFieldList
     * @param string[] $saveFieldList
     * @return $this
     */
    public function setSaveFieldList($saveFieldList)
    {
        $this->container['saveFieldList'] = $saveFieldList;

        return $this;
    }

    /**
     * Gets version
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     * @param string $version
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets streamName
     * @return string
     */
    public function getStreamName()
    {
        return $this->container['streamName'];
    }

    /**
     * Sets streamName
     * @param string $streamName
     * @return $this
     */
    public function setStreamName($streamName)
    {
        $this->container['streamName'] = $streamName;

        return $this;
    }

    /**
     * Gets resID
     * @return string
     */
    public function getResID()
    {
        return $this->container['resID'];
    }

    /**
     * Sets resID
     * @param string $resID
     * @return $this
     */
    public function setResID($resID)
    {
        $this->container['resID'] = $resID;

        return $this;
    }

    /**
     * Gets order
     * @return int
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     * @param int $order
     * @return $this
     */
    public function setOrder($order)
    {
        $this->container['order'] = $order;

        return $this;
}

}
