<?php
/**
 * VserversserverNamepublishersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WowzaApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Topix\Hackademy\WowzaApi\Test\Api;

use Topix\Hackademy\WowzaApi\ApiException;

/**
 * VserversserverNamepublishersApiTest Class Doc Comment
 *
 * @category Class
 * @package  WowzaApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VserversserverNamepublishersApiTest extends TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deletePublisherConfig
     *
     * Deletes the specified Publisher configuration.
     *
     */
    public function testDeletePublisherConfig()
    {

    }
    /**
     * Test case for deletePublisherConfig3
     *
     * Deletes the specified Publisher configuration.
     *
     */
    public function testDeletePublisherConfig3()
    {

    }
    /**
     * Test case for getPublisherConfig
     *
     * Retrieves the specified Publisher configuration.
     *
     */
    public function testGetPublisherConfig()
    {

    }
    /**
     * Test case for getPublisherConfig3
     *
     * Retrieves the specified Publisher configuration.
     *
     */
    public function testGetPublisherConfig3()
    {

    }
    /**
     * Test case for getPublishersConfig
     *
     * Retrieves the list of server Publishers.
     *
     */
    public function testGetPublishersConfig()
    {

    }
    /**
     * Test case for getPublishersConfig3
     *
     * Retrieves the list of server Publishers.
     *
     */
    public function testGetPublishersConfig3()
    {

    }
    /**
     * Test case for postPublisherConfig
     *
     * Adds the specified Publisher configuration.
     *
     */
    public function testPostPublisherConfig()
    {

    }
    /**
     * Test case for postPublisherConfig3
     *
     * Adds the specified Publisher configuration.
     *
     */
    public function testPostPublisherConfig3()
    {

    }
    /**
     * Test case for postPublishersConfig
     *
     * Adds a new Publisher to the list.
     *
     */
    public function testPostPublishersConfig()
    {

    }
    /**
     * Test case for postPublishersConfig3
     *
     * Adds a new Publisher to the list.
     *
     */
    public function testPostPublishersConfig3()
    {

    }
    /**
     * Test case for putPublisherConfig
     *
     * Updates the specified Publisher configuration.
     *
     */
    public function testPutPublisherConfig()
    {

    }
    /**
     * Test case for putPublisherConfig3
     *
     * Updates the specified Publisher configuration.
     *
     */
    public function testPutPublisherConfig3()
    {

    }
}
