site_name: Wowza-Rest Api Documentation
site_description: Documentation for the Wowza Rest API developed by TOP-IX
site_author: TOP-IX HackAdemy
site_url: http://top-ix.org
repo_url: https://github.com/topix-hackademy/contact-tools

docs_dir: docs
site_dir: site
theme: mkdocs

pages:
- Home: index.md
- Legacy-Docs Api:
  - legacy-docs/Api/RestinfoApi.md
  - legacy-docs/Api/VmachinemonitoringcurrentApi.md
  - legacy-docs/Api/VmachinemonitoringhistoricApi.md
  - legacy-docs/Api/VserversApi.md
  - legacy-docs/Api/VserversserverNamelicensesApi.md
  - legacy-docs/Api/VserversserverNamelistenersApi.md
  - legacy-docs/Api/VserversserverNamelogjApi.md
  - legacy-docs/Api/VserversserverNamemediacacheApi.md
  - legacy-docs/Api/VserversserverNamemediacastersApi.md
  - legacy-docs/Api/VserversserverNamemonitoringApi.md
  - legacy-docs/Api/VserversserverNamepublishersApi.md
  - legacy-docs/Api/VserversserverNamestatusApi.md
  - legacy-docs/Api/VserversserverNametranscoderApi.md
  - legacy-docs/Api/VserversserverNametuneApi.md
  - legacy-docs/Api/VserversserverNameusersApi.md
  - legacy-docs/Api/VserversserverNamevhostsApi.md
  - legacy-docs/Api/VserversserverNamevhostsvhostNameapplicationsApi.md
- Legacy-Docs Model:
  - legacy-docs/Model/StartupStreamsConfig.md
  - legacy-docs/Model/StreamConfigurationConfig.md
  - legacy-docs/Model/StreamFileAction.md
  - legacy-docs/Model/StreamFileAppAction.md
  - legacy-docs/Model/StreamFileAppConfig.md
  - legacy-docs/Model/StreamFileAppConfigAdv.md
  - legacy-docs/Model/StreamFileConfig.md
  - legacy-docs/Model/StreamFileConfigAdv.md
  - legacy-docs/Model/StreamFilesAppConfig.md
  - legacy-docs/Model/StreamFilesConfig.md
  - legacy-docs/Model/StreamGroupAction.md
  - legacy-docs/Model/StreamGroupConfig.md
  - legacy-docs/Model/StreamGroupsConfig.md
  - legacy-docs/Model/StreamRecorderAction.md
  - legacy-docs/Model/StreamRecorderConfig.md
  - legacy-docs/Model/StreamRecordersConfig.md
  - legacy-docs/Model/TranscoderAppConfig.md
  - legacy-docs/Model/TranscoderAppConfigAdv.md
  - legacy-docs/Model/TranscoderConfig.md
  - legacy-docs/Model/TranscoderEncodeAppConfig.md
  - legacy-docs/Model/TranscoderEncodeAppConfigAdv.md
  - legacy-docs/Model/TranscoderEncodeConfig.md
  - legacy-docs/Model/TranscoderEncodeConfigAdv.md
  - legacy-docs/Model/TranscoderEncodesAppConfig.md
  - legacy-docs/Model/TranscoderEncodesConfig.md
  - legacy-docs/Model/TranscoderMemberConfig.md
  - legacy-docs/Model/TranscoderOverlayDecodeAppConfig.md
  - legacy-docs/Model/TranscoderOverlayDecodeConfig.md
  - legacy-docs/Model/TranscoderOverlayEncodeAppConfig.md
  - legacy-docs/Model/TranscoderOverlayEncodeConfig.md
  - legacy-docs/Model/TranscoderStreamNameGroupAppConfig.md
  - legacy-docs/Model/TranscoderStreamNameGroupConfig.md
  - legacy-docs/Model/TranscoderStreamNameGroupsAppConfig.md
  - legacy-docs/Model/TranscoderStreamNameGroupsConfig.md
  - legacy-docs/Model/TranscoderTemplateAction.md
  - legacy-docs/Model/TranscoderTemplateAppAction.md
  - legacy-docs/Model/TranscoderTemplateAppConfig.md
  - legacy-docs/Model/TranscoderTemplateAppConfigAdv.md
  - legacy-docs/Model/TranscoderTemplateConfig.md
  - legacy-docs/Model/TranscoderTemplateConfigAdv.md
  - legacy-docs/Model/TranscoderTemplatesAppConfig.md
  - legacy-docs/Model/TranscoderTemplatesConfig.md
  - legacy-docs/Model/UserConfig.md
  - legacy-docs/Model/UsersConfig.md
  - legacy-docs/Model/VHostAction.md
  - legacy-docs/Model/VHostConfig.md
  - legacy-docs/Model/VHostConfigAdv.md
  - legacy-docs/Model/VHostShortObject.md
  - legacy-docs/Model/VHostTuneConfig.md
  - legacy-docs/Model/VHostsConfig.md
  - legacy-docs/Model/VerimatrixStreamMapConfig.md
  - legacy-docs/Model/VerimatrixStreamMapsConfig.md
  - legacy-docs/Model/VideoSettings.md
  - legacy-docs/Model/WMSLoggerConfig.md
  - legacy-docs/Model/AdvancedSetting.md
  - legacy-docs/Model/AppShortObject.md
  - legacy-docs/Model/ApplicationAction.md
  - legacy-docs/Model/ApplicationConfig.md
  - legacy-docs/Model/ApplicationConfigAdv.md
  - legacy-docs/Model/ApplicationsConfig.md
  - legacy-docs/Model/BuyDRMStreamMapConfig.md
  - legacy-docs/Model/BuyDRMStreamMapsConfig.md
  - legacy-docs/Model/CurrentApplicationStatistics.md
  - legacy-docs/Model/CurrentIncomingStreamStatistics.md
  - legacy-docs/Model/CurrentMachineStatistics.md
  - legacy-docs/Model/CurrentVHostStatistics.md
  - legacy-docs/Model/DRMConfig.md
  - legacy-docs/Model/DRMConfigAdv.md
  - legacy-docs/Model/DVRConfig.md
  - legacy-docs/Model/DVRConfigAdv.md
  - legacy-docs/Model/DefaultStreamRecorderConfig.md
  - legacy-docs/Model/DvrRESTConverterStore.md
  - legacy-docs/Model/DvrRESTConverterStoreAction.md
  - legacy-docs/Model/DvrRESTConverterStores.md
  - legacy-docs/Model/DvrRESTConverterStoresAction.md
  - legacy-docs/Model/HistoricApplicationStatistics.md
  - legacy-docs/Model/HistoricMachineStatistics.md
  - legacy-docs/Model/HistoricServerStatistics.md
  - legacy-docs/Model/HistoricVHostStatistics.md
  - legacy-docs/Model/HostPortConfig.md
  - legacy-docs/Model/HostPortConfigAdv.md
  - legacy-docs/Model/HostPortsConfig.md
  - legacy-docs/Model/HostportsTuneConfig.md
  - legacy-docs/Model/IncomingStreamAction.md
  - legacy-docs/Model/IncomingStreamConfig.md
  - legacy-docs/Model/InstanceAction.md
  - legacy-docs/Model/InstanceConfig.md
  - legacy-docs/Model/InstancesConfig.md
  - legacy-docs/Model/Integer.md
  - legacy-docs/Model/LiveEncoderConfig.md
  - legacy-docs/Model/Log4jAction.md
  - legacy-docs/Model/Log4js.md
  - legacy-docs/Model/Log4jsAction.md
  - legacy-docs/Model/Long.md
  - legacy-docs/Model/MediaCacheApplicationStoreAction.md
  - legacy-docs/Model/MediaCacheConfig.md
  - legacy-docs/Model/MediaCacheConfig3.md
  - legacy-docs/Model/MediaCacheConfigAdv.md
  - legacy-docs/Model/MediaCacheSourceConfig.md
  - legacy-docs/Model/MediaCacheSourceConfig3.md
  - legacy-docs/Model/MediaCacheSourceConfigAdv.md
  - legacy-docs/Model/MediaCacheSourceConfigAdv3.md
  - legacy-docs/Model/MediaCacheSourcesConfig.md
  - legacy-docs/Model/MediaCacheSourcesConfig3.md
  - legacy-docs/Model/MediaCacheStoreAction.md
  - legacy-docs/Model/MediaCacheStoreConfig.md
  - legacy-docs/Model/MediaCacheStoreConfig3.md
  - legacy-docs/Model/MediaCacheStoreConfigAdv.md
  - legacy-docs/Model/MediaCacheStoreList.md
  - legacy-docs/Model/MediaCacheStoresConfig.md
  - legacy-docs/Model/MediaCacheStoresConfig3.md
  - legacy-docs/Model/MediaCasterConfig.md
  - legacy-docs/Model/MediaCastersConfig.md
  - legacy-docs/Model/ModuleConfig.md
  - legacy-docs/Model/ModulesConfig.md
  - legacy-docs/Model/MonitoringConfig.md
  - legacy-docs/Model/OutgoingStreamConfig.md
  - legacy-docs/Model/Output.md
  - legacy-docs/Model/PublisherAppConfig.md
  - legacy-docs/Model/PublisherConfig.md
  - legacy-docs/Model/PublisherConfig3.md
  - legacy-docs/Model/PublisherVhostConfig.md
  - legacy-docs/Model/PublishersAppConfig.md
  - legacy-docs/Model/PublishersConfig.md
  - legacy-docs/Model/PublishersConfig3.md
  - legacy-docs/Model/PublishersVhostConfig.md
  - legacy-docs/Model/PushPublishStreamAppAction.md
  - legacy-docs/Model/PushPublishStreamAppConfig.md
  - legacy-docs/Model/PushPublishStreamsAppConfig.md
  - legacy-docs/Model/RESTInfoConfig.md
  - legacy-docs/Model/RTMP.md
  - legacy-docs/Model/SDPFileAction.md
  - legacy-docs/Model/SDPFileAppAction.md
  - legacy-docs/Model/SDPFileAppConfig.md
  - legacy-docs/Model/SDPFileConfig.md
  - legacy-docs/Model/SDPFilesAppConfig.md
  - legacy-docs/Model/SDPFilesConfig.md
  - legacy-docs/Model/SMILFileAction.md
  - legacy-docs/Model/SMILFileAppAction.md
  - legacy-docs/Model/SMILFileAppConfig.md
  - legacy-docs/Model/SMILFileConfig.md
  - legacy-docs/Model/SMILFileStreamConfig.md
  - legacy-docs/Model/SMILFilesAppConfig.md
  - legacy-docs/Model/SMILFilesConfig.md
  - legacy-docs/Model/SSLConfig.md
  - legacy-docs/Model/SecurityConfig.md
  - legacy-docs/Model/ServerAction.md
  - legacy-docs/Model/ServerConfig.md
  - legacy-docs/Model/ServerConfigAdv.md
  - legacy-docs/Model/ServerLicensesConfig.md
  - legacy-docs/Model/ServerListenerConfig.md
  - legacy-docs/Model/ServerListenersConfig.md
  - legacy-docs/Model/ServerLogFileConfig.md
  - legacy-docs/Model/ServerLogFileDownloadConfig.md
  - legacy-docs/Model/ServerLogFilesConfig.md
  - legacy-docs/Model/ServerLogShortObject.md
  - legacy-docs/Model/ServerLogTypesConfig.md
  - legacy-docs/Model/ServerLogsConfig.md
  - legacy-docs/Model/ServerStatusConfig.md
  - legacy-docs/Model/ServerTuneConfig.md
  - legacy-docs/Model/ServersConfig.md
  - legacy-docs/Model/ShortObject.md
  - legacy-docs/Model/ShortUrlEncoderConfig.md
  - legacy-docs/Model/SourceControlAction.md
  - legacy-docs/Model/SourceControlConfig.md
  - legacy-docs/Model/SourceDriverNamesList.md
  - legacy-docs/Model/StartupStreamConfig.md
